 export const services = [
  {title: "Embdded Systems ", description: ".Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.", image: "./assets/embedded.jpg"},
  {title: "Internet Of Things", description: "etur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.", image: "./assets/embedded.jpg"},
  {title: "Artificial Intelligence", description: ".Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.", image: "./assets/embedded.jpg"},
  {title: "Research & Devolopement", description: ".Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.", image: "./assets/embedded.jpg"},
  {title: "Automation", description: "L.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.", image: "./assets/embedded.jpg"},
  {title: "Testing", description: ".Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit.", image: "./assets/embedded.jpg"},
];
export const abouts=[{img:"./assets/Youssef.jpg", nomPrenom:"Youssef Kaffel", job:"FULL STACK JAVA SCRIPT", linkedIn:"https://www.linkedin.com/in/youssefkaffel/", portfolio:"https://youssefkaffel.github.io/portfolio/"},
{img:"./assets/Brahim.png", nomPrenom:"Brahim Trigui", job:"FULL STACK JAVA SCRIPT", linkedIn:"https://www.linkedin.com/in/brahim-trigui/", portfolio:"https://triguib.github.io/MyPortfolio/"},{img:"./assets/Brahim.png", nomPrenom:"Brahim Trigui", job:"FULL STACK JAVA SCRIPT", linkedIn:"https://www.linkedin.com/in/brahim-trigui/", portfolio:"https://triguib.github.io/MyPortfolio/"},{img:"./assets/Brahim.png", nomPrenom:"Brahim Trigui", job:"FULL STACK JAVA SCRIPT", linkedIn:"https://www.linkedin.com/in/brahim-trigui/", portfolio:"https://triguib.github.io/MyPortfolio/"},{img:"./assets/Brahim.png", nomPrenom:"Brahim Trigui", job:"FULL STACK JAVA SCRIPT", linkedIn:"https://www.linkedin.com/in/brahim-trigui/", portfolio:"https://triguib.github.io/MyPortfolio/"},{img:"./assets/Brahim.png", nomPrenom:"Brahim Trigui", job:"FULL STACK JAVA SCRIPT", linkedIn:"https://www.linkedin.com/in/brahim-trigui/", portfolio:"https://triguib.github.io/MyPortfolio/"}]
